before:
  hooks:
    - go mod download

builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - linux
    - windows
    - darwin
    main: ./cmd/main.go

dockers:
  - image_templates:
    - "gilbsgilbs/glloq:{{ .Tag }}"
    - "gilbsgilbs/glloq:v{{ .Major }}"
    - "gilbsgilbs/glloq:v{{ .Major }}.{{ .Minor }}"
    - "gilbsgilbs/glloq:latest"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
