before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    main: ./cmd/main.go

dockers:
  - image_templates:
    - "gilbsgilbs/glloq:{{ .Tag }}"
    - "gilbsgilbs/glloq:{{ .Major }}"
    - "gilbsgilbs/glloq:{{ .Major }}.{{ .Minor }}"
    - "gilbsgilbs/glloq:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    - "gilbsgilbs/glloq:latest"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
      {{- end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  prerelease: auto
