version: "3.8"

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: glloq
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: glloq
      MYSQL_PASSWORD: glloq
      MYSQL_DATABASE: glloq
      MYSQL_ROOT_PASSWORD: root
